services:
  frontend:
    build:
      context: ./EdgeDetectr-Frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - OPERATOR_PROCESS=/app/operators/build
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/results:/app/results
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge